### ISSUE TITLE
Improve/extend seed for noise and benchmark

### ISSUE THREAD

**Issue by stklik** [altaris/noisy-moo#7]
Currently it looks like seed is only available for algorithm descriptions (i.e. the thing passed to `minimize`)
We should update nmoo to allow general seeding the RNG.

Specifically we need two features:
- **Noise should have a seed-parameter** (e.g. with a default value of 1 or 12345) that is passed into the RNG
https://github.com/altaris/noisy-moo/blob/707e307a11914e9fa951622df85089dfff7be8a1/nmoo/noises/gaussian.py#L79

- **Benchmarks should allow for specification of a seed**, that is passed into the wrappers and the algorithm.
This is a bit more complicated, since we have repetitions.
Easiest solution: specify an ("initial") seed for the `Benchmark` as parameter, which is used for each (problem x algorithm). Then, for each repetition use (seed++).
Alternative: manually specify a list of seeds (one for each repetition).

To consider: what if we want to have something "special" such as  "all algorithms should have the same seed, but problems with different seeds" (or vice versa)
Thus, maybe seeding should be handled in several places:
1. Algorithm description (specify directly) & Noise description (specify directly)
2. Benchmark (use this if not already in 1. or 2.)

Also: How should we deal with "restarting / continuing / extending" benchmarks? What if there is a different seed specification?
(this might be a non-issue and left to the user to care about)

**Comment by altaris** [comment]
Hi,

1. Seeding on a per-layer basis is possible as of bb808a37b26a9b3e042c74ab6d0363355453b86f (see https://github.com/altaris/noisy-moo/blob/bb808a37b26a9b3e042c74ab6d0363355453b86f/nmoo/noises/gaussian.py#L60 and https://github.com/altaris/noisy-moo/blob/bb808a37b26a9b3e042c74ab6d0363355453b86f/nmoo/noises/uniform.py#L83 ).

2. Seeding at the benchmark level (i.e. passing a seed in the `Benchmark` constructor and having it be propagated) isn't supported. I'm not sure it makes sense to implement that since you can already set seeds when wrapping your problems in noisy layers. For this reason, I think it's a non-issue.
